#! /bin/sh

sxhkd &
# picom &

feh --bg-center ~/pictures/wallhaven-72rd8e_1920x1080.png

bspc monitor HDMI-0 -d 1 2 3
bspc monitor DP-5 -d 4 5 6 7
bspc monitor eDP-1-1 -d 8 9 0

bspc config border_width         2
bspc config window_gap          12

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a Zathura state=tiled
bspc rule -a osbuddy state=floating
bspc rule -a brave state=tiled
bspc rule -a flameshot state=tiled
bspc rule -a zoom state=tiled
bspc rule -a DBeaver desktop='^1' state=tiled
bspc rule -a Postman desktop='^2'
bspc rule -a Xournalpp desktop='^3'
bspc rule -a Chromium desktop='^4'
bspc rule -a "Microsoft Teams - Preview" desktop='^8' state=tiled
bspc rule -a discord desktop='^9' state=tiled
bspc rule -a firefox desktop='^4'
bspc rule -a Brave-browser desktop='^4'

wmname LG3D &

$HOME/.config/polybar/blocks/launch.sh

# # Kill all running instances
# killall -a picom
# 
# # Wait until processes have been shut down
# while pgrep -x picom >/dev/null; do sleep 0.2; done
# 
# # Launch picom
# picom --conf $HOME/.picom.conf

# run the xrandr command if an external monitor is connected to the
# laptop.  This must be executed before the polybar command, so that
# polybar can set the two separate bars properly.
# xrandr --output eDP-1 --mode 1920x1080 --rotate normal --output HDMI-1-1 --primary --mode 1920x1080 --rotate normal --right-of eDP-1

# bspc monitor eDP-1 -d 6 7 8 9 10
